openapi: 3.0.3
info:
  title: Bookstore
  description: The best store to find your favorite books!
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /books:
    get:
      responses:
        200:
          description: Accepted
          content:
            application/json:
              schema:
                type: string
    post:
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /book:
    get:
      parameters:
        - name: isbn
          in: path
          schema:
            type: string
      responses:
        200:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    Book:
      type: object
      properties:
        isbn:
          type: integer
          format: int64
        title:
          type: string
        author:
          type: string
        type:
          type: string
          enum:
            - HORROR
            - ROMANCE
            - DRAMA
            - FICTION
            - TECHNICAL
        published:
          type: date
      required:
        - isbn
